@startuml "vcmi-1.32-classes"

skinparam defaultTextAlignment center

!procedure $desc($txt)
<font:Arial><color:Gray><i>// $txt</i></color></font>
!endprocedure

title "VCMI-1.3.2 class diagram (inexhaustive)"

'''' Declarations to stylize the diagram ''''
hide circle
set namespaceSeparator none

skinparam ClassFontStyle bold
skinparam ClassFontName monospaced
skinparam ClassAttributeFontName monospaced
skinparam ClassAttributeIconSize 0
skinparam DefaultTextAlignment left


'''' Attributes and methods '''


class CVCMIServer {
    gh          CGameHandler
    state       EServerState    $desc("SHUTDOWN / LOBBY / GAMEPLAY")
    acceptor    TAcceptor       $desc("accepts client connections")
    connections CConnection     $desc("stores client connections")
    --
    run()
}

class CApplier<T> {
    apps                        map<short, T*>
    --
    registerType(B *b, D *d)    $desc("B and D are template types, calls addApplier with each")
    getApplier(short ID)        T*
    addApplier(short ID)        $desc("the template type is used for the added item's type")
}

@enduml
