@startuml "vcmi-1.32-connector-v2-render"

title "VCMI-1.3.2 connector-v2 render"

skinparam sequenceBoxBorderColor #FFF

!$nbsp = "<U+00A0>"

' workaround the fact that text alignment can only be
' set globally. Using hspace(n) returns N monospaced
' $nbsp chars
!function $hspace($length)
  !$res = ""
  !$i = $length
  !while $i > 0
    !$res = $res + $nbsp
    !$i = $i - 1
  !endwhile
  !return "<font:monospaced>"+$res+"</font>"
!endfunction

!function $desc($txt)
  !return "<font:Arial><color:Gray><i>// "+$txt+"</i></color></font>"
!endfunction

!function $wait($set)
  !if ($set == 0)
    !return "<back:red>cond.wait</back>\n"+$lock(0)
  !endif

  !return "<color:yellow><back:blue>cond.wait</back></color>\n"+$lock(1,1)
!endfunction

!function $notify()
  !return "<color:blue>cond.notify</color>"
!endfunction

!function $lock($obtain)
  !if ($obtain == 1)
    !return "<back:yellow>obtain lock</back>"
  !else
    !return "<color:yellow><back:black>release lock</back></color>"
  !endif
!endfunction

!function $lock($obtain, $success)
  !if ($obtain == 0 || $success == 1)
    !return $lock($obtain)
  !endif
  ' failed to obtain
  !return "<back:yellow><color:red>obtain lock</color></back>"
!endfunction

!function $sharevar($name)
  !return "<color:gray>"+$name+"</color>"
!endfunction

box T1
participant "//Env//" as env
participant "//pyconnector//" as py
participant "//cppconnector//\n$desc(T1)" as cpp1
end box

box T2
participant "//cppconnector//\n$desc(T2)" as cpp2
participant "//AAI//" as aai
participant "//BAI//" as bai
participant "//VCMI Client//" as vcmiclient
end box

activate cpp1
activate py
activate env

vcmiclient o-> bai ++ : activeStack
bai -> aai ++ : getAction(Result)
aai -> cpp2 ++ : F_GetAction(Result)\n$desc("from cbprovider")
cpp2 <--> cpp1 :
cpp1 --> py -- : <<P_result>>
py --> env -- : <<obs>>
[<-- env -- : obs
cpp2 -> cpp2 : $wait(0)

== render start ==

[-> env ++ : render
env -> py ++ : render
py -> cpp1 ++ : render
cpp1 -> cpp1 : $lock(1,1)
cpp1 <--> cpp2 : $sharevar(Action)
cpp1 -> cpp1 : $notify()
cpp1 -> cpp1 : $wait(0)
cpp2 -> cpp2 : $wait(1)
cpp2 --> aai -- : $lock(0)\n<<Action>>\n$desc("render")
aai --> bai ++ : bai.render()
note right: same thread\nrecursive call
bai --> aai -- : <<string>>
aai -> cpp2 ++ : F_GetAction(Result)\n$desc("render data")
cpp2 -> cpp2 : $lock(1,1)
cpp2 <--[#gray]> cpp1 : $sharevar(P_Result)
cpp2 -> cpp2 : $notify()
cpp2 -> cpp2 : $lock(0)
cpp1 -> cpp1 : $wait(1)
cpp2 -> cpp2 : $lock(1,0)
cpp1 --> py -- : $lock(0)\n<<P_result>>
cpp2 -> cpp2 : $lock(1,1)
cpp2 -> cpp2 : $wait(0)
py --> env -- : <<string>>
[<-- env -- : string

== render end ==

@enduml
